id: I707C87F4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T06:55:00+00:00'
last_modified: '2022-06-08T13:09:18.591120+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24104
  title: སྡེ་དགེའི་བྲོ་ཆེན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    C50D:
      image_group_id: I1KG24255
      title: Volume 1 of sde dge'i bro chen/
      total_pages: 364
      order: 1
      base_file: C50D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
