id: P006969
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24104
  title: སྡེ་དགེའི་བྲོ་ཆེན།
  author: ''
  volumes:
    b3af6c55cee04cf38d8311b7681aca49:
      image_group_id: I1KG24255
      title: ''
      volume_number: 1
      total_pages: 364
ebook_metadata:
  title: སྡེ་དགེའི་བྲོ་ཆེན།
  author: ''
  sku: P006969
  cover: cover.jpg
  layers:
  - pagination
